### ISSUE TITLE
bang

### ISSUE THREAD

**Issue by Zaxzz** [EmptyWork/emptywork.github.io#201]
bisa minta nomer wa nya? saya mau deploy ke netlify ko error : 
Deploy did not succeed: Deploy directory "_site" does not exist

**Comment by EmptyWork** [comment]
Hello, untuk masalah itu, karena hasil compile website yang dilakukan dari eleventy itu jadinya ke folder `/public`, jadi kamu bisa ganti di settingan netlify bagian `publish directory` ke `public` atau kamu bisa ganti di `.eleventy.js` baris ke 104 bagian output jadi `_site`

```js
...  

return {
    templateFormats: ['md', 'njk', 'html', 'liquid'],

    markdownTemplateEngine: 'liquid',
    htmlTemplateEngine: 'njk',
    dataTemplateEngine: 'njk',
    dir: {
      data: '_data',
      input: 'src',
      output: 'public', // ubah ke _site
    },
  }
```
