### ISSUE TITLE
One deployment was unsuccessful.

### ISSUE THREAD

**Issue by domainbf** [EmptyWork/emptywork.github.io#202]
The deployment of vercel and netlify was not successful

I really like your work.

**Comment by EmptyWork** [comment]
Hello there, 

I think you are having the same problem as #201, You need to update couple of things, the reason of the development aren't going through is because I modified the output directory from `_site` to `public` (I am talking in case you are using netlify as the hosting platform), so there is several ways for you to fix this problem:

## Changing the `.eleventy.js` file

You can go to the `.eleventy.js` and go to the line 104, then change it to `_site`

```js
...  

return {
    templateFormats: ['md', 'njk', 'html', 'liquid'],

    markdownTemplateEngine: 'liquid',
    htmlTemplateEngine: 'njk',
    dataTemplateEngine: 'njk',
    dir: {
      data: '_data',
      input: 'src',
      output: 'public', // change these to _site
    },
  }
```

## Changing the development source on Netlify

Or you can either go to your netlify dashboard -> build & development -> continuous deployment, under the build settings then change the publish directory from `_site` to `public`.

I hope that is fixing your problem, in-case it doesn't fix it, please attach the error code or logs that netlify or vercel throw when you try do deploy the site.

**Comment by domainbf** [comment]
Thank you for your guidance.

I have revised it according to your guidance. Public has been replaced with _ site

The installation has been completed, but the home page is messy and I don't know what went wrong.

Https://661cca4bbbe1231083fcba01--wubaohu.netlify.app/

**Comment by EmptyWork** [comment]
The CSS aren't properly render/process, I am not really sure why that happened, because when I redeploy my website it doesn't produce the same problem as yours, but in my opinion you could try to redeploy again to see if its just some kind of hiccup on netlify side, before you try to redeploy, make sure to check the build command on netlify: 

it supposed to be `npm run build` and it will be great if you could attach the deploy log from netlify for me to troubleshoot it.

### More information
I also found a problem with your deployment, you change the code on `redirect.js` it will resulting on never-end redirection, you could just remove the file and then go to `src/_includes/layouts/primary.njk` and `src/_includes/layouts/secondary.njk` to remove the reference to the file, the reason I have that file because I want people who access the website (mine) through netlify domain to be redirect to my main domain without changing the setting on my netlify domain access.

**Comment by domainbf** [comment]
5:27:42 PM: build-image version: fcb0c1b3ada6d25c1cb58e8bc514f5f23cc14f15 (focal)
5:27:42 PM: buildbot version: ee2ef905a4bdb64f7733dd60a718aa00319e6f82
5:27:42 PM: Fetching cached dependencies
5:27:42 PM: Failed to fetch cache, continuing with build
5:27:42 PM: Starting to prepare the repo for build
5:27:42 PM: No cached dependencies found. Cloning fresh repo
5:27:42 PM: git clone --filter=blob:none https://github.com/domainbf/emptywork
5:27:43 PM: Preparing Git Reference refs/heads/main
5:27:46 PM: Starting to install dependencies
5:27:48 PM: Python version set to 3.8
5:27:48 PM: Attempting Ruby version 2.7.2, read from environment
5:27:49 PM: Using Ruby version 2.7.2
5:27:50 PM: Started restoring cached go cache
5:27:50 PM: Finished restoring cached go cache
5:27:52 PM: go version go1.19.13 linux/amd64
5:27:52 PM: Using PHP version 8.0
5:27:54 PM: Downloading and installing node v18.20.2...
5:27:54 PM: Downloading https://nodejs.org/dist/v18.20.2/node-v18.20.2-linux-x64.tar.xz...
5:27:55 PM: Computing checksum with sha256sum
5:27:55 PM: Checksums matched!
5:27:57 PM: Now using node v18.20.2 (npm v10.5.0)
5:27:57 PM: Enabling Node.js Corepack
5:27:58 PM: Started restoring cached build plugins
5:27:58 PM: Finished restoring cached build plugins
5:27:58 PM: Started restoring cached corepack dependencies
5:27:58 PM: Finished restoring cached corepack dependencies
5:27:58 PM: No npm workspaces detected
5:27:58 PM: Started restoring cached node modules
5:27:58 PM: Finished restoring cached node modules
5:27:58 PM: Installing npm packages using npm version 10.5.0
5:28:02 PM: added 298 packages, and audited 299 packages in 4s
5:28:02 PM: 78 packages are looking for funding
5:28:02 PM:   run `npm fund` for details
5:28:02 PM: found 0 vulnerabilities
5:28:02 PM: npm packages installed
5:28:03 PM: Successfully installed dependencies
5:28:03 PM: Starting build script
5:28:06 PM: Detected 1 framework(s)
5:28:06 PM: "eleventy" at version "2.0.1"
5:28:06 PM: Section completed: initializing
5:28:08 PM: ​
5:28:08 PM: Netlify Build                                                 
5:28:08 PM: ────────────────────────────────────────────────────────────────
5:28:08 PM: ​
5:28:08 PM: ❯ Version
5:28:08 PM:   @netlify/build 29.39.1
5:28:08 PM: ​
5:28:08 PM: ❯ Flags
5:28:08 PM:   baseRelDir: true
5:28:08 PM:   buildId: 661cf2ffb70e8b36cd959b99
5:28:08 PM:   deployId: 661cf2ffb70e8b36cd959b9b
5:28:08 PM: ​
5:28:08 PM: ❯ Current directory
5:28:08 PM:   /opt/build/repo
5:28:08 PM: ​
5:28:08 PM: ❯ Config file
5:28:08 PM:   /opt/build/repo/netlify.toml
5:28:08 PM: ​
5:28:08 PM: ❯ Context
5:28:08 PM:   production
5:28:08 PM: ​
5:28:08 PM: Build command from Netlify app                                
5:28:08 PM: ────────────────────────────────────────────────────────────────
5:28:08 PM: ​
5:28:08 PM: $ npm run build
5:28:08 PM: > emptywork.github.io@1.0.0 build
5:28:08 PM: > npm run sass:compressed && eleventy
5:28:08 PM: > emptywork.github.io@1.0.0 sass:compressed
5:28:08 PM: > sass --style=compressed --no-source-map src/assets/scss:public/css/
5:28:10 PM: Post processing - redirect rules
5:28:10 PM: Post processing done
5:28:10 PM: Section completed: postprocessing
5:28:10 PM: Starting post processing
5:28:10 PM: Skipping form detection
5:28:10 PM: Post processing - header rules
5:28:10 PM: [11ty] Writing _site/articles/project/2021-10-29-jobfair-website/index.html from ./src/articles/project/2021-10-29-jobfair-website.md (liquid)
5:28:10 PM: [11ty] Writing _site/articles/project/2021-10-29-ukimexpo2019-website/index.html from ./src/articles/project/2021-10-29-ukimexpo2019-website.md (liquid)
5:28:10 PM: [11ty] Writing _site/articles/project/2022-04-13-event-betaqris-website/index.html from ./src/articles/project/2022-04-13-event-betaqris-website.md (liquid)
5:28:10 PM: [11ty] Writing _site/articles/project/2023-05-20-event-ambonfunrun-website/index.html from ./src/articles/project/2023-05-20-event-ambonfunrun-website.md (liquid)
5:28:10 PM: [11ty] Writing _site/articles/prototype/2021-ci3-implementation/index.html from ./src/articles/prototype/2021-ci3-implementation.md (liquid)
5:28:10 PM: [11ty] Writing _site/articles/prototype/2021-ew-javascript/index.html from ./src/articles/prototype/2021-ew-javascript.md (liquid)
5:28:10 PM: [11ty] Writing _site/articles/prototype/2021-sai-go-in-the-rain-website/index.html from ./src/articles/prototype/2021-sai-go-in-the-rain-website.md (liquid)
5:28:10 PM: [11ty] Writing _site/feed.xml from ./src/feed.njk
5:28:10 PM: [11ty] Writing _site/multimedia/index.html from ./src/multimedia.njk
5:28:10 PM: [11ty] Writing _site/sitemap.xml from ./src/sitemap.njk
5:28:10 PM: [11ty] Writing _site/admin/index.html from ./src/admin/index.html (njk)
5:28:10 PM: [11ty] Writing _site/blog/index.html from ./src/blog.njk
5:28:10 PM: [11ty] Writing _site/contact/index.html from ./src/contact.njk
5:28:10 PM: [11ty] Writing _site/error/index.html from ./src/error.njk
5:28:10 PM: [11ty] Writing _site/index.html from ./src/index.njk
5:28:10 PM: [11ty] Writing _site/articles/blog/2023-02-16-the-first-day-of-interning-in-maluku-province-bank-indonesia-representative-office/index.html from ./src/articles/blog/2023-02-16-the-first-day-of-interning-in-maluku-province-bank-indonesia-representative-office.md (liquid)
5:28:10 PM: [11ty] Writing _site/articles/blog/2022-04-13-accessibility-the-future-of-web-development/index.html from ./src/articles/blog/2022-04-13-accessibility-the-future-of-web-development.md (liquid)
5:28:10 PM: [11ty] Copied 68 files / Wrote 17 files in 0.38 seconds (22.4ms each, v2.0.1)
5:28:10 PM: ​
5:28:10 PM: (build.command completed in 2.1s)
5:28:10 PM: ​
5:28:10 PM: Deploy site                                                   
5:28:10 PM: ────────────────────────────────────────────────────────────────
5:28:10 PM: ​
5:28:10 PM: Starting to deploy site from '_site'
5:28:10 PM: Calculating files to upload
5:28:10 PM: 1 new files to upload
5:28:10 PM: 0 new functions to upload
5:28:10 PM: Section completed: deploying
5:28:10 PM: Site deploy was successfully initiated
5:28:10 PM: ​
5:28:10 PM: (Deploy site completed in 260ms)
5:28:10 PM: ​
5:28:10 PM: Netlify Build Complete                                        
5:28:10 PM: ────────────────────────────────────────────────────────────────
5:28:10 PM: ​
5:28:10 PM: (Netlify Build completed in 2.4s)
5:28:11 PM: Site is live ✨
5:28:11 PM: Caching artifacts
5:28:11 PM: Started saving node modules
5:28:11 PM: Finished saving node modules
5:28:11 PM: Started saving build plugins
5:28:11 PM: Finished saving build plugins
5:28:11 PM: Started saving corepack cache
5:28:11 PM: Finished saving corepack cache
5:28:11 PM: Started saving pip cache
5:28:11 PM: Finished saving pip cache
5:28:11 PM: Started saving emacs cask dependencies
5:28:11 PM: Finished saving emacs cask dependencies
5:28:11 PM: Started saving maven dependencies
5:28:11 PM: Finished saving maven dependencies
5:28:11 PM: Started saving boot dependencies
5:28:11 PM: Finished saving boot dependencies
5:28:11 PM: Started saving rust rustup cache
5:28:11 PM: Finished saving rust rustup cache
5:28:11 PM: Started saving go dependencies
5:28:11 PM: Finished saving go dependencies
5:28:39 PM: Build script success
5:28:39 PM: Section completed: building
5:28:40 PM: Uploading Cache of size 110.7MB
5:28:41 PM: Section completed: cleanup
5:28:41 PM: Finished processing build request in 59.029s
5:32:51 PM: [ERROR] Deploy logs are currently unavailable. We are working on resolving the issue.
Hello, thank you for your guidance, I re-pull, reinstall, show that everything is not wrong, or the call to css error, I do not know what went wrong

**Comment by EmptyWork** [comment]
Hi, I know what the cause of the problem, it is in-fact the same as previous one, I made hardcode reference to the output of the css file, I just notice it after I read the log you provided, the output of the code aren't changing, the problem should be easy to fix, go to the `package.json` then do as following:

```json
...
  "scripts": {
    "sass": "sass --no-source-map src/assets/scss/:public/css/", // change the public/css to _site/css
    "sass:compressed": "sass --style=compressed --no-source-map src/assets/scss:public/css/", // change the public/css to _site/css
    "watch": "npm-run-all --parallel watch:*",
    "watch:eleventy": "eleventy --serve",
    "watch:sass": "npm run sass:compressed -- --watch",
    "build": "npm run sass:compressed && eleventy",
    "start": "npm-run-all sass:compressed --parallel watch:*",
    "dev": "npm run watch"
  },

...
```

It should be like these:

```json
...
  "scripts": {
    "sass": "sass --no-source-map src/assets/scss/:_site/css/", 
    "sass:compressed": "sass --style=compressed --no-source-map src/assets/scss:_site/css/", 
    "watch": "npm-run-all --parallel watch:*",
    "watch:eleventy": "eleventy --serve",
    "watch:sass": "npm run sass:compressed -- --watch",
    "build": "npm run sass:compressed && eleventy",
    "start": "npm-run-all sass:compressed --parallel watch:*",
    "dev": "npm run watch"
  },

...
```

**Comment by domainbf** [comment]
Yes, it has been solved perfectly.

Thank you.

**Comment by EmptyWork** [comment]
Great to heard that, I will close this issue then
